import { LegalLayout } from '@/components/legal/LegalLayout';

export const metadata = {
  title: 'Privacy Policy — Bookam',
  description: "How BookamFast Nigeria Ltd. collects, uses, and protects your personal data on the Bookam platform.",
};

export default function PrivacyPolicyPage() {
  return (
    <LegalLayout lastUpdated="July 2026">
        <h1 className="legal-title">BOOKAM PRIVACY POLICY</h1>
        <h2 className="legal-h2">1. INTRODUCTION</h2>
        <h3 className="legal-h3">1.1 About Bookam</h3>
        <p className="legal-p">Bookam is a digital hospitality and booking platform owned and operated by BookamFast Nigeria Ltd. (“Bookam”, “Company”, “we”, “our”, or “us”).</p>
        <p className="legal-p">Bookam enables users to discover, compare, reserve, and pay for hospitality and lifestyle services including:</p>
        <p className="legal-p">Hotels;</p>
        <p className="legal-p">Shortlet apartments;</p>
        <p className="legal-p">Event centres;</p>
        <p className="legal-p">Car rentals;</p>
        <p className="legal-p">Yacht rentals; and</p>
        <p className="legal-p">Other hospitality-related services offered by independent third-party providers.</p>
        <p className="legal-p">This Privacy Policy explains how we collect, use, process, store, disclose, transfer, and protect personal data obtained through our website, mobile application, customer support channels, social media platforms, business partnerships, and other services associated with Bookam.</p>
        <h3 className="legal-h3">1.2 Our Commitment to Privacy</h3>
        <p className="legal-p">Bookam is committed to protecting the privacy, confidentiality, integrity, and security of personal information entrusted to us.</p>
        <p className="legal-p">We process personal data in accordance with:</p>
        <p className="legal-p">The Nigeria Data Protection Act, 2023 (NDPA);</p>
        <p className="legal-p">The Nigeria Data Protection Regulation (NDPR);</p>
        <p className="legal-p">Applicable regulations issued by the Nigeria Data Protection Commission (NDPC);</p>
        <p className="legal-p">Relevant consumer protection laws;</p>
        <p className="legal-p">Applicable provisions of the General Data Protection Regulation (GDPR) where relevant; and</p>
        <p className="legal-p">International best practices relating to privacy and data governance.</p>
        <h3 className="legal-h3">1.3 Scope</h3>
        <p className="legal-p">This Privacy Policy applies to:</p>
        <p className="legal-p">Users;</p>
        <p className="legal-p">Guests;</p>
        <p className="legal-p">Customers;</p>
        <p className="legal-p">Vendors;</p>
        <p className="legal-p">Property owners;</p>
        <p className="legal-p">Hotel operators;</p>
        <p className="legal-p">Event centre operators;</p>
        <p className="legal-p">Car rental providers;</p>
        <p className="legal-p">Yacht providers;</p>
        <p className="legal-p">Service partners;</p>
        <p className="legal-p">Website visitors; and</p>
        <p className="legal-p">Prospective customers interacting with Bookam.</p>
        <h2 className="legal-h2">2. DEFINITIONS</h2>
        <p className="legal-p">For purposes of this Policy:</p>
        <p className="legal-p">“Personal Data” means any information relating to an identified or identifiable natural person.</p>
        <p className="legal-p">“Data Subject” means the individual to whom personal data relates.</p>
        <p className="legal-p">“Processing” means any operation performed on personal data including collection, recording, storage, use, disclosure, transmission, deletion, or destruction.</p>
        <p className="legal-p">“Provider” means any hotel, shortlet operator, event centre owner, property manager, car rental operator, yacht provider, airport transfer provider, or other hospitality service provider listed on Bookam.</p>
        <p className="legal-p">“User” means any individual who accesses or uses the Bookam Platform.</p>
        <p className="legal-p">“Platform” means the Bookam website, mobile applications, APIs, booking systems, customer support systems, and related services.</p>
        <h2 className="legal-h2">3. PERSONAL DATA WE COLLECT</h2>
        <h3 className="legal-h3">3.1 Information You Provide Directly</h3>
        <p className="legal-p">We may collect:</p>
        <p className="legal-p">Identity Information</p>
        <p className="legal-p">Full name;</p>
        <p className="legal-p">Date of birth;</p>
        <p className="legal-p">Gender;</p>
        <p className="legal-p">Government-issued identification details;</p>
        <p className="legal-p">Passport details (where required);</p>
        <p className="legal-p">National Identification Number (where required);</p>
        <p className="legal-p">Driver’s licence information (for vehicle rentals).</p>
        <p className="legal-p">Contact Information</p>
        <p className="legal-p">Email address;</p>
        <p className="legal-p">Phone number;</p>
        <p className="legal-p">Residential address;</p>
        <p className="legal-p">Billing address.</p>
        <p className="legal-p">Account Information</p>
        <p className="legal-p">Username;</p>
        <p className="legal-p">Password;</p>
        <p className="legal-p">Profile photograph;</p>
        <p className="legal-p">Preferences;</p>
        <p className="legal-p">Communication settings.</p>
        <p className="legal-p">Booking Information</p>
        <p className="legal-p">Check-in and check-out dates;</p>
        <p className="legal-p">Event dates;</p>
        <p className="legal-p">Guest information;</p>
        <p className="legal-p">Number of attendees;</p>
        <p className="legal-p">Property preferences;</p>
        <p className="legal-p">Travel information;</p>
        <p className="legal-p">Special requests.</p>
        <p className="legal-p">Payment Information</p>
        <p className="legal-p">Bookam does not store complete card details.</p>
        <p className="legal-p">Payments are processed through secure third-party payment processors such as Paystack and other approved providers.</p>
        <p className="legal-p">We may receive:</p>
        <p className="legal-p">Transaction references;</p>
        <p className="legal-p">Payment status;</p>
        <p className="legal-p">Payment amount;</p>
        <p className="legal-p">Payment method type;</p>
        <p className="legal-p">Billing information.</p>
        <h2 className="legal-h2">4. INFORMATION WE COLLECT AUTOMATICALLY</h2>
        <p className="legal-p">When you use Bookam, we may automatically collect:</p>
        <p className="legal-p">Device Information</p>
        <p className="legal-p">Device type;</p>
        <p className="legal-p">Device identifier;</p>
        <p className="legal-p">Browser type;</p>
        <p className="legal-p">Operating system;</p>
        <p className="legal-p">Mobile network information.</p>
        <p className="legal-p">Location Information</p>
        <p className="legal-p">Subject to your consent, we may collect:</p>
        <p className="legal-p">GPS location;</p>
        <p className="legal-p">IP-based location;</p>
        <p className="legal-p">Device location.</p>
        <p className="legal-p">Location information may be used to:</p>
        <p className="legal-p">Suggest nearby listings;</p>
        <p className="legal-p">Improve search results;</p>
        <p className="legal-p">Prevent fraud;</p>
        <p className="legal-p">Enhance platform functionality.</p>
        <h2 className="legal-h2">5. INFORMATION WE RECEIVE FROM THIRD PARTIES</h2>
        <p className="legal-p">We may receive information from:</p>
        <p className="legal-p">Providers</p>
        <p className="legal-p">Booking confirmations;</p>
        <p className="legal-p">Property information;</p>
        <p className="legal-p">Guest verification information;</p>
        <p className="legal-p">Incident reports;</p>
        <p className="legal-p">Refund requests;</p>
        <p className="legal-p">Damage reports.</p>
        <p className="legal-p">Payment Processors</p>
        <p className="legal-p">Payment confirmations;</p>
        <p className="legal-p">Fraud alerts;</p>
        <p className="legal-p">Transaction status updates.</p>
        <p className="legal-p">Marketing Partners</p>
        <p className="legal-p">Referral information;</p>
        <p className="legal-p">Campaign analytics;</p>
        <p className="legal-p">Lead-generation data.</p>
        <p className="legal-p">Identity Verification Providers</p>
        <p className="legal-p">Where required, we may obtain verification information to confirm identity and reduce fraud.</p>
        <h2 className="legal-h2">6. LEGAL BASIS FOR PROCESSING</h2>
        <p className="legal-p">Bookam processes personal data only where a lawful basis exists.</p>
        <p className="legal-p">These lawful bases include:</p>
        <p className="legal-p">Contract Performance</p>
        <p className="legal-p">To:</p>
        <p className="legal-p">Process bookings;</p>
        <p className="legal-p">Manage reservations;</p>
        <p className="legal-p">Facilitate payments;</p>
        <p className="legal-p">Provide customer support.</p>
        <p className="legal-p">Legal Obligations</p>
        <p className="legal-p">To:</p>
        <p className="legal-p">Comply with regulatory requirements;</p>
        <p className="legal-p">Respond to lawful requests;</p>
        <p className="legal-p">Meet tax and accounting obligations.</p>
        <p className="legal-p">Legitimate Interests</p>
        <p className="legal-p">To:</p>
        <p className="legal-p">Improve services;</p>
        <p className="legal-p">Detect fraud;</p>
        <p className="legal-p">Secure the platform;</p>
        <p className="legal-p">Conduct analytics;</p>
        <p className="legal-p">Protect users and providers.</p>
        <p className="legal-p">Consent</p>
        <p className="legal-p">Where required, we rely on consent for:</p>
        <p className="legal-p">Marketing communications;</p>
        <p className="legal-p">Certain cookies;</p>
        <p className="legal-p">Location tracking;</p>
        <p className="legal-p">Optional services.</p>
        <p className="legal-p">Consent may be withdrawn at any time.</p>
        <h2 className="legal-h2">7. HOW WE USE PERSONAL DATA</h2>
        <p className="legal-p">Bookam may collect, use, process, and disclose personal data for the following purposes:</p>
        <h3 className="legal-h3">7.1 Platform Operations</h3>
        <p className="legal-p">We use personal data to:</p>
        <p className="legal-p">Create and manage user accounts;</p>
        <p className="legal-p">Facilitate bookings and reservations;</p>
        <p className="legal-p">Process payments and refunds;</p>
        <p className="legal-p">Confirm bookings and communicate booking details;</p>
        <p className="legal-p">Coordinate with Providers regarding reservations;</p>
        <p className="legal-p">Manage cancellations, modifications, and rescheduling requests;</p>
        <p className="legal-p">Verify user identity where necessary;</p>
        <p className="legal-p">Provide customer support services.</p>
        <h3 className="legal-h3">7.2 Service Improvement</h3>
        <p className="legal-p">We may use data to:</p>
        <p className="legal-p">Improve platform functionality;</p>
        <p className="legal-p">Enhance user experience;</p>
        <p className="legal-p">Analyze user behavior and booking trends;</p>
        <p className="legal-p">Develop new products and services;</p>
        <p className="legal-p">Optimize search and recommendation features.</p>
        <h3 className="legal-h3">7.3 Security and Fraud Prevention</h3>
        <p className="legal-p">We process personal data to:</p>
        <p className="legal-p">Detect fraud and suspicious activity;</p>
        <p className="legal-p">Prevent unauthorized access;</p>
        <p className="legal-p">Investigate complaints;</p>
        <p className="legal-p">Verify transactions;</p>
        <p className="legal-p">Protect users, providers, and Bookam from abuse.</p>
        <h3 className="legal-h3">7.4 Communications</h3>
        <p className="legal-p">We may contact users regarding:</p>
        <p className="legal-p">Booking confirmations;</p>
        <p className="legal-p">Booking reminders;</p>
        <p className="legal-p">Service updates;</p>
        <p className="legal-p">Customer support requests;</p>
        <p className="legal-p">Changes to our services;</p>
        <p className="legal-p">Security notifications;</p>
        <p className="legal-p">Policy updates.</p>
        <h3 className="legal-h3">7.5 Marketing</h3>
        <p className="legal-p">Where permitted by law or where consent has been obtained, we may use personal data to:</p>
        <p className="legal-p">Send promotional offers;</p>
        <p className="legal-p">Share newsletters;</p>
        <p className="legal-p">Inform users of new listings;</p>
        <p className="legal-p">Notify users of discounts and campaigns;</p>
        <p className="legal-p">Provide personalized recommendations.</p>
        <p className="legal-p">Users may opt out of marketing communications at any time.</p>
        <h2 className="legal-h2">8. SHARING AND DISCLOSURE OF PERSONAL DATA</h2>
        <p className="legal-p">Bookam respects user privacy and does not sell personal data.</p>
        <p className="legal-p">However, we may share information in the following circumstances:</p>
        <h3 className="legal-h3">8.1 Sharing With Providers</h3>
        <p className="legal-p">To facilitate bookings, we may share booking-related information with relevant Providers.</p>
        <p className="legal-p">This may include:</p>
        <p className="legal-p">Name;</p>
        <p className="legal-p">Contact details;</p>
        <p className="legal-p">Booking dates;</p>
        <p className="legal-p">Guest information;</p>
        <p className="legal-p">Special requests;</p>
        <p className="legal-p">Identity verification information where required.</p>
        <p className="legal-p">Providers may only use such information for purposes connected with the relevant booking.</p>
        <h3 className="legal-h3">8.2 Payment Service Providers</h3>
        <p className="legal-p">We may share information with approved payment processors including:</p>
        <p className="legal-p">Paystack;</p>
        <p className="legal-p">Flutterwave;</p>
        <p className="legal-p">Banks;</p>
        <p className="legal-p">Financial institutions;</p>
        <p className="legal-p">Payment gateway providers.</p>
        <p className="legal-p">Such parties process payment information in accordance with their own privacy policies and applicable laws.</p>
        <h3 className="legal-h3">8.3 Professional Advisors</h3>
        <p className="legal-p">We may disclose information to:</p>
        <p className="legal-p">Lawyers;</p>
        <p className="legal-p">Auditors;</p>
        <p className="legal-p">Accountants;</p>
        <p className="legal-p">Consultants;</p>
        <p className="legal-p">Insurers.</p>
        <p className="legal-p">Where necessary for legal, regulatory, compliance, or business purposes.</p>
        <h3 className="legal-h3">8.4 Regulatory Authorities</h3>
        <p className="legal-p">We may disclose information where required by:</p>
        <p className="legal-p">Courts;</p>
        <p className="legal-p">Government agencies;</p>
        <p className="legal-p">Law enforcement agencies;</p>
        <p className="legal-p">Regulatory authorities;</p>
        <p className="legal-p">Tax authorities.</p>
        <h2 className="legal-h2">9. RELATIONSHIP BETWEEN BOOKAM AND THIRD-PARTY PROVIDERS</h2>
        <p className="legal-p">Bookam operates as a technology-enabled marketplace and booking facilitation platform.</p>
        <p className="legal-p">Bookam does not own, lease, manage, operate, control, or provide the hotels, shortlets, event centres, vehicles, yachts, airport transfer services, or other hospitality services listed on the Platform.</p>
        <p className="legal-p">Providers remain independent third parties.</p>
        <p className="legal-p">Accordingly:</p>
        <p className="legal-p">Providers are responsible for their own data processing activities;</p>
        <p className="legal-p">Providers are responsible for maintaining their own privacy practices;</p>
        <p className="legal-p">Providers may act as independent data controllers in relation to personal information received from Bookam;</p>
        <p className="legal-p">Bookam is not responsible for privacy breaches caused by independent Providers outside Bookam’s control.</p>
        <p className="legal-p">Users are encouraged to review any privacy notices provided by Providers where applicable.</p>
        <h2 className="legal-h2">10. COOKIES AND TRACKING TECHNOLOGIES</h2>
        <p className="legal-p">Bookam uses cookies and similar technologies to improve functionality and user experience.</p>
        <h3 className="legal-h3">10.1 What Are Cookies?</h3>
        <p className="legal-p">Cookies are small data files stored on a user’s device when visiting a website or using certain applications.</p>
        <h3 className="legal-h3">10.2 Types of Cookies We Use</h3>
        <p className="legal-p">Essential Cookies</p>
        <p className="legal-p">Required for:</p>
        <p className="legal-p">Login functionality;</p>
        <p className="legal-p">Security;</p>
        <p className="legal-p">Session management;</p>
        <p className="legal-p">Platform operations.</p>
        <p className="legal-p">Performance Cookies</p>
        <p className="legal-p">Used to:</p>
        <p className="legal-p">Measure platform performance;</p>
        <p className="legal-p">Improve functionality;</p>
        <p className="legal-p">Identify technical issues.</p>
        <p className="legal-p">Analytics Cookies</p>
        <p className="legal-p">Used to understand:</p>
        <p className="legal-p">User behavior;</p>
        <p className="legal-p">Traffic patterns;</p>
        <p className="legal-p">Search activity;</p>
        <p className="legal-p">Booking trends.</p>
        <p className="legal-p">Marketing Cookies</p>
        <p className="legal-p">Used to:</p>
        <p className="legal-p">Deliver relevant advertisements;</p>
        <p className="legal-p">Measure campaign performance;</p>
        <p className="legal-p">Personalize promotional content.</p>
        <p className="legal-p">Users may modify cookie settings through browser or device settings.</p>
        <h2 className="legal-h2">11. INTERNATIONAL DATA TRANSFERS</h2>
        <p className="legal-p">Bookam may use third-party service providers located in various jurisdictions.</p>
        <p className="legal-p">Accordingly, personal data may be transferred outside Nigeria.</p>
        <p className="legal-p">Where international transfers occur, Bookam shall take reasonable steps to ensure that appropriate safeguards are implemented, including:</p>
        <p className="legal-p">Contractual protections;</p>
        <p className="legal-p">Data transfer agreements;</p>
        <p className="legal-p">Adequacy mechanisms;</p>
        <p className="legal-p">Security controls.</p>
        <p className="legal-p">Bookam will endeavor to ensure that transferred data receives a level of protection consistent with applicable data protection laws.</p>
        <h2 className="legal-h2">12. DATA SECURITY</h2>
        <p className="legal-p">Bookam employs reasonable technical, administrative, and organizational safeguards to protect personal data.</p>
        <p className="legal-p">Such safeguards may include:</p>
        <p className="legal-p">Encryption technologies;</p>
        <p className="legal-p">Access controls;</p>
        <p className="legal-p">Multi-factor authentication;</p>
        <p className="legal-p">Secure servers;</p>
        <p className="legal-p">Monitoring systems;</p>
        <p className="legal-p">Vulnerability assessments;</p>
        <p className="legal-p">Employee confidentiality obligations.</p>
        <p className="legal-p">Despite these measures, no electronic system can be guaranteed to be completely secure.</p>
        <p className="legal-p">Users acknowledge that transmission of information over the internet carries inherent risks.</p>
        <h2 className="legal-h2">13. DATA RETENTION</h2>
        <p className="legal-p">Bookam retains personal data only for as long as reasonably necessary to:</p>
        <p className="legal-p">Provide services;</p>
        <p className="legal-p">Fulfill contractual obligations;</p>
        <p className="legal-p">Comply with legal requirements;</p>
        <p className="legal-p">Resolve disputes;</p>
        <p className="legal-p">Enforce agreements;</p>
        <p className="legal-p">Protect legitimate business interests.</p>
        <p className="legal-p">Retention periods may vary depending on:</p>
        <p className="legal-p">Nature of the data;</p>
        <p className="legal-p">Type of transaction;</p>
        <p className="legal-p">Applicable legal requirements.</p>
        <p className="legal-p">Upon expiration of applicable retention periods, personal data may be:</p>
        <p className="legal-p">Deleted;</p>
        <p className="legal-p">Anonymized;</p>
        <p className="legal-p">Archived where legally required.</p>
        <h2 className="legal-h2">14. DATA SUBJECT RIGHTS</h2>
        <p className="legal-p">Subject to applicable law, users may exercise the following rights:</p>
        <h3 className="legal-h3">14.1 Right of Access</h3>
        <p className="legal-p">Users may request information regarding personal data held by Bookam.</p>
        <h3 className="legal-h3">14.2 Right to Rectification</h3>
        <p className="legal-p">Users may request correction of inaccurate or incomplete information.</p>
        <h3 className="legal-h3">14.3 Right to Erasure</h3>
        <p className="legal-p">Users may request deletion of personal data where legally permissible.</p>
        <h3 className="legal-h3">14.4 Right to Restrict Processing</h3>
        <p className="legal-p">Users may request limitations on certain processing activities.</p>
        <h3 className="legal-h3">14.5 Right to Object</h3>
        <p className="legal-p">Users may object to processing based on legitimate interests.</p>
        <h3 className="legal-h3">14.6 Right to Withdraw Consent</h3>
        <p className="legal-p">Where processing relies on consent, users may withdraw consent at any time.</p>
        <h3 className="legal-h3">14.7 Right to Data Portability</h3>
        <p className="legal-p">Where applicable, users may request transfer of personal data in a structured format.</p>
        <h3 className="legal-h3">14.8 Right to Lodge a Complaint</h3>
        <p className="legal-p">Users may submit complaints to:</p>
        <p className="legal-p">Bookam;</p>
        <p className="legal-p">The Nigeria Data Protection Commission (NDPC);</p>
        <p className="legal-p">Other competent regulatory authorities where applicable.</p>
        <p className="legal-p">Requests may be submitted through Bookam’s designated privacy contact channels.</p>
        <h2 className="legal-h2">15. MARKETING COMMUNICATIONS</h2>
        <p className="legal-p">Bookam may send:</p>
        <p className="legal-p">Promotional messages;</p>
        <p className="legal-p">Newsletters;</p>
        <p className="legal-p">Product announcements;</p>
        <p className="legal-p">Campaign updates;</p>
        <p className="legal-p">Service recommendations.</p>
        <p className="legal-p">Users may unsubscribe at any time through:</p>
        <p className="legal-p">Account settings;</p>
        <p className="legal-p">Email unsubscribe links;</p>
        <p className="legal-p">Customer support channels.</p>
        <p className="legal-p">Bookam will continue sending transactional communications necessary for bookings and account administration.</p>
        <h2 className="legal-h2">16. CHILDREN’S PRIVACY</h2>
        <p className="legal-p">Bookam’s services are intended for persons who are at least eighteen (18) years of age.</p>
        <p className="legal-p">Bookam does not knowingly collect personal information from children.</p>
        <p className="legal-p">Where Bookam becomes aware that personal data has been collected from a child without lawful authorization, reasonable steps will be taken to delete such information.</p>
        <h2 className="legal-h2">17. THIRD-PARTY SERVICES AND LINKS</h2>
        <p className="legal-p">The Platform may contain links to:</p>
        <p className="legal-p">Hotels;</p>
        <p className="legal-p">Event centres;</p>
        <p className="legal-p">Third-party websites;</p>
        <p className="legal-p">Payment gateways;</p>
        <p className="legal-p">Social media platforms;</p>
        <p className="legal-p">Service providers.</p>
        <p className="legal-p">Bookam is not responsible for:</p>
        <p className="legal-p">Content;</p>
        <p className="legal-p">Privacy practices;</p>
        <p className="legal-p">Security measures;</p>
        <p className="legal-p">Data processing activities</p>
        <p className="legal-p">of such third parties.</p>
        <p className="legal-p">Users should review applicable third-party privacy policies independently.</p>
        <h2 className="legal-h2">18. PERSONAL DATA BREACHES</h2>
        <p className="legal-p">In the event of a personal data breach that is likely to result in risk to the rights and freedoms of individuals, Bookam shall take reasonable steps to:</p>
        <p className="legal-p">Investigate the incident;</p>
        <p className="legal-p">Mitigate harm;</p>
        <p className="legal-p">Notify affected individuals where required;</p>
        <p className="legal-p">Notify competent regulatory authorities where legally required;</p>
        <p className="legal-p">Implement corrective measures.</p>
        <h2 className="legal-h2">19. COMPLAINTS AND DATA PROTECTION ENQUIRIES</h2>
        <p className="legal-p">Questions, requests, complaints, or concerns regarding privacy matters may be directed to:</p>
        <p className="legal-p">BookamFast Nigeria Ltd.</p>
        <p className="legal-p">Bookam Platform</p>
        <p className="legal-p">Email: contact@bookamfast.com</p>
        <p className="legal-p">Phone: +234 9034145636</p>
        <p className="legal-p">Address: Lagos, Nigeria.</p>
        <p className="legal-p">Where a complaint cannot be resolved internally, users may contact the Nigeria Data Protection Commission (NDPC) or other competent authorities.</p>
        <h2 className="legal-h2">20. CHANGES TO THIS PRIVACY POLICY</h2>
        <p className="legal-p">Bookam reserves the right to amend, modify, or update this Privacy Policy from time to time.</p>
        <p className="legal-p">Changes may be communicated through:</p>
        <p className="legal-p">The Platform;</p>
        <p className="legal-p">Email;</p>
        <p className="legal-p">Mobile notifications;</p>
        <p className="legal-p">Website notices;</p>
        <p className="legal-p">Other reasonable communication channels.</p>
        <p className="legal-p">Continued use of the Platform following publication of an updated Privacy Policy constitutes acceptance of the revised version.</p>
        <h2 className="legal-h2">21. CONTACT INFORMATION</h2>
        <p className="legal-p">BookamFast Nigeria Ltd.</p>
        <p className="legal-p">Owners and Operators of the Bookam Platform</p>
        <p className="legal-p">Address:</p>
        <p className="legal-p">Lagos, Nigeria</p>
        <p className="legal-p"><strong>General Enquiries:</strong> contact@bookamfast.com</p>
        <p className="legal-p">contact@bookamfast.com</p>
        <p className="legal-p">Telephone:</p>
        <p className="legal-p">09034145636</p>
        <p className="legal-p">Business Hours:</p>
        <p className="legal-p">9:00 AM – 9:00 PM (WAT)</p>
    </LegalLayout>
  );
}