import { LegalLayout } from '@/components/legal/LegalLayout';

export const metadata = {
  title: 'Terms and Conditions — Bookam',
  description: 'The Terms and Conditions governing use of the Bookam platform, operated by BookamFast Nigeria Ltd.',
};

export default function TermsPage() {
  return (
    <LegalLayout lastUpdated="July 2026">
        <h1 className="legal-title">BOOKAM TERMS AND CONDITIONS</h1>
        <h2 className="legal-part">PART 1</h2>
        <p className="legal-p">INTRODUCTION, DEFINITIONS, PLATFORM ROLE, ELIGIBILITY, LISTINGS, PROPERTY VERIFICATION AND BOOKINGS</p>
        <h2 className="legal-h2">1. INTRODUCTION</h2>
        <h3 className="legal-h3">1.1 Acceptance of Terms</h3>
        <p className="legal-p">These Terms and Conditions (“Terms”) govern access to and use of the Bookam mobile application, website, booking platform, payment features, customer support services, and all related services (collectively referred to as the “Platform”).</p>
        <p className="legal-p">By accessing, browsing, registering on, making a booking through, making a payment through, or otherwise using the Platform, you acknowledge that you have read, understood, and agreed to be bound by these Terms and all policies incorporated herein by reference.</p>
        <p className="legal-p">If you do not agree with these Terms, you must not use the Platform.</p>
        <h3 className="legal-h3">1.2 Binding Agreement</h3>
        <p className="legal-p">These Terms constitute a legally binding agreement between BookamFast Nigeria Ltd. (“Bookam”, “Company”, “we”, “our”, or “us”) and any individual or entity using the Platform (“User”, “Guest”, “you”, or “your”).</p>
        <h3 className="legal-h3">1.3 Geographic Scope</h3>
        <p className="legal-p">The Platform currently facilitates bookings primarily within Lagos State, Nigeria. Bookam reserves the right to expand its operations to additional cities, states, and jurisdictions at its sole discretion.</p>
        <h3 className="legal-h3">1.4 Related Policies</h3>
        <p className="legal-p">The following policies form an integral part of these Terms:</p>
        <p className="legal-p">a. Privacy Policy;</p>
        <p className="legal-p">b. Refund and Cancellation Policy;</p>
        <p className="legal-p">c. Caution Fee Policy;</p>
        <p className="legal-p">d. Provider Guidelines;</p>
        <p className="legal-p">e. Booking-Specific Policies displayed before payment;</p>
        <p className="legal-p">f. Any additional policies published on the Platform from time to time.</p>
        <p className="legal-p">In the event of any conflict between these Terms and a booking-specific policy, the booking-specific policy shall prevail solely for that booking.</p>
        <h2 className="legal-h2">2. DEFINITIONS</h2>
        <p className="legal-p">For the purposes of these Terms:</p>
        <p className="legal-p">“Account” means a registered user profile on the Platform.</p>
        <p className="legal-p">“App” means the Bookam mobile application.</p>
        <p className="legal-p">“Booking” means a reservation request made through the Platform for accommodation, venue usage, transportation, or related services.</p>
        <p className="legal-p">“Booking Confirmation” means an official confirmation issued by Bookam confirming a successful reservation.</p>
        <p className="legal-p">“Caution Fee” means a refundable security deposit intended to cover damages, losses, excessive cleaning, overstays, rule violations, or other liabilities.</p>
        <p className="legal-p">“Company” means BookamFast Nigeria Ltd. and its affiliates.</p>
        <p className="legal-p">“Event Centre” means any venue listed for meetings, conferences, weddings, parties, corporate events, social gatherings, exhibitions, or similar purposes.</p>
        <p className="legal-p">“Guest” means the individual making or benefiting from a booking.</p>
        <p className="legal-p">“Hotel” means any hotel, resort, guest house, lodge, serviced accommodation, or hospitality facility listed on the Platform.</p>
        <p className="legal-p">“Listing” means any property, venue, vehicle, yacht, or service displayed on the Platform.</p>
        <p className="legal-p">“Payment Gateway” means any third-party payment processor approved by Bookam.</p>
        <p className="legal-p">“Provider” means any property owner, hotel operator, apartment manager, shortlet operator, event centre owner, car rental operator, yacht operator, property manager, authorised representative, or service provider listed on the Platform.</p>
        <p className="legal-p">“Service Fee” means any fee charged by Bookam for facilitating bookings or providing related services.</p>
        <p className="legal-p">“Shortlet” means a furnished apartment, serviced apartment, vacation rental, or temporary accommodation available for short-term occupancy.</p>
        <p className="legal-p">“User” means any person or entity accessing or using the Platform.</p>
        <p className="legal-p">“Verified Listing” means a listing that has undergone verification procedures determined by Bookam.</p>
        <h2 className="legal-h2">3. NATURE AND ROLE OF THE PLATFORM</h2>
        <h3 className="legal-h3">3.1 Marketplace Function</h3>
        <p className="legal-p">Bookam operates as a technology-enabled marketplace that enables users to discover, compare, request, reserve, and pay for accommodation, venues, transportation, and hospitality-related services offered by independent third-party providers.</p>
        <h3 className="legal-h3">3.2 No Ownership or Operation</h3>
        <p className="legal-p">Bookam does not own, lease, manage, operate, control, supervise, maintain, or provide:</p>
        <p className="legal-p">a. Hotels;</p>
        <p className="legal-p">b. Shortlets;</p>
        <p className="legal-p">c. Apartments;</p>
        <p className="legal-p">d. Event Centres;</p>
        <p className="legal-p">e. Vehicles;</p>
        <p className="legal-p">f. Yachts;</p>
        <p className="legal-p">g. Any other services listed on the Platform.</p>
        <p className="legal-p">All such services are independently owned and operated by third-party providers.</p>
        <h3 className="legal-h3">3.3 Independent Providers</h3>
        <p className="legal-p">Providers are independent contractors and third parties.</p>
        <p className="legal-p">Nothing in these Terms creates any:</p>
        <p className="legal-p">a. Partnership;</p>
        <p className="legal-p">b. Joint venture;</p>
        <p className="legal-p">c. Employment relationship;</p>
        <p className="legal-p">d. Agency relationship;</p>
        <p className="legal-p">e. Franchise relationship;</p>
        <p className="legal-p">between Bookam and any Provider.</p>
        <h3 className="legal-h3">3.4 No Party to Provider-Guest Relationship</h3>
        <p className="legal-p">The accommodation agreement, rental arrangement, venue-use agreement, transportation arrangement, or service agreement exists solely between the User and the Provider.</p>
        <p className="legal-p">Bookam merely facilitates the transaction and is not a contracting party to such arrangements.</p>
        <h3 className="legal-h3">3.5 Platform Services</h3>
        <p className="legal-p">Bookam may provide:</p>
        <p className="legal-p">a. Listing publication;</p>
        <p className="legal-p">b. Booking facilitation;</p>
        <p className="legal-p">c. Payment collection;</p>
        <p className="legal-p">d. Booking confirmations;</p>
        <p className="legal-p">e. Customer support;</p>
        <p className="legal-p">f. Complaint handling assistance;</p>
        <p className="legal-p">g. Verification services;</p>
        <p className="legal-p">h. Administrative support;</p>
        <p className="legal-p">i. Promotional and marketing services.</p>
        <h2 className="legal-h2">4. ELIGIBILITY AND ACCOUNT REGISTRATION</h2>
        <h3 className="legal-h3">4.1 Minimum Age Requirement</h3>
        <p className="legal-p">Users must be at least eighteen (18) years old to create an account, make a booking, or use the Platform.</p>
        <h3 className="legal-h3">4.2 Legal Capacity</h3>
        <p className="legal-p">Users represent and warrant that they possess full legal capacity to enter into legally binding agreements.</p>
        <h3 className="legal-h3">4.3 Registration Information</h3>
        <p className="legal-p">Users may be required to provide:</p>
        <p className="legal-p">a. Full name;</p>
        <p className="legal-p">b. Email address;</p>
        <p className="legal-p">c. Telephone number;</p>
        <p className="legal-p">d. Residential address;</p>
        <p className="legal-p">e. Identification details;</p>
        <p className="legal-p">f. Payment information;</p>
        <p className="legal-p">g. Any additional information reasonably required by Bookam.</p>
        <h3 className="legal-h3">4.4 Accuracy of Information</h3>
        <p className="legal-p">Users must provide accurate, complete, and up-to-date information at all times.</p>
        <p className="legal-p">Providing false information constitutes a material breach of these Terms.</p>
        <h3 className="legal-h3">4.5 Account Security</h3>
        <p className="legal-p">Users are solely responsible for:</p>
        <p className="legal-p">a. Protecting login credentials;</p>
        <p className="legal-p">b. Maintaining account confidentiality;</p>
        <p className="legal-p">c. Activities conducted through their account;</p>
        <p className="legal-p">d. Preventing unauthorised access.</p>
        <h3 className="legal-h3">4.6 Verification</h3>
        <p className="legal-p">Bookam may request identity verification documents before approving certain bookings or account activities.</p>
        <h3 className="legal-h3">4.7 Suspension and Termination</h3>
        <p className="legal-p">Bookam may suspend, restrict, or terminate accounts where it reasonably believes a user has engaged in:</p>
        <p className="legal-p">a. Fraud;</p>
        <p className="legal-p">b. Chargeback abuse;</p>
        <p className="legal-p">c. Misrepresentation;</p>
        <p className="legal-p">d. Property damage;</p>
        <p className="legal-p">e. Harassment;</p>
        <p className="legal-p">f. Illegal conduct;</p>
        <p className="legal-p">g. Repeated complaints;</p>
        <p className="legal-p">h. Violation of these Terms.</p>
        <h2 className="legal-h2">5. LISTINGS AND PROPERTY INFORMATION</h2>
        <h3 className="legal-h3">5.1 Provider Responsibility</h3>
        <p className="legal-p">Providers are solely responsible for all listing content, including:</p>
        <p className="legal-p">a. Photographs;</p>
        <p className="legal-p">b. Amenities;</p>
        <p className="legal-p">c. Pricing;</p>
        <p className="legal-p">d. Availability;</p>
        <p className="legal-p">e. Capacity limits;</p>
        <p className="legal-p">f. House rules;</p>
        <p className="legal-p">g. Venue rules;</p>
        <p className="legal-p">h. Cancellation terms;</p>
        <p className="legal-p">i. Descriptions;</p>
        <p className="legal-p">j. Location information.</p>
        <h3 className="legal-h3">5.2 Information Displayed</h3>
        <p className="legal-p">Listings may include:</p>
        <p className="legal-p">a. Images;</p>
        <p className="legal-p">b. Descriptions;</p>
        <p className="legal-p">c. Facilities;</p>
        <p className="legal-p">d. Pricing;</p>
        <p className="legal-p">e. Availability;</p>
        <p className="legal-p">f. Event restrictions;</p>
        <p className="legal-p">g. Booking conditions;</p>
        <p className="legal-p">h. Cancellation policies;</p>
        <p className="legal-p">i. Caution fee requirements;</p>
        <p className="legal-p">j. Check-in and check-out instructions.</p>
        <h3 className="legal-h3">5.4 Listing Modifications</h3>
        <p className="legal-p">Bookam reserves the right to:</p>
        <p className="legal-p">a. Modify listings;</p>
        <p className="legal-p">b. Suspend listings;</p>
        <p className="legal-p">c. Remove listings;</p>
        <p className="legal-p">d. Correct errors;</p>
        <p className="legal-p">e. Update information;</p>
        <p className="legal-p">at any time without prior notice.</p>
        <h2 className="legal-h2">6. PROPERTY VERIFICATION</h2>
        <h3 className="legal-h3">6.1 Verification Procedures</h3>
        <p className="legal-p">Bookam may undertake verification procedures before approving listings.</p>
        <p className="legal-p">Verification procedures may include:</p>
        <p className="legal-p">a. Site inspections;</p>
        <p className="legal-p">b. Document review;</p>
        <p className="legal-p">c. Identity verification;</p>
        <p className="legal-p">d. Property assessment;</p>
        <p className="legal-p">e. Ownership confirmation;</p>
        <p className="legal-p">f. Photograph verification.</p>
        <h3 className="legal-h3">6.2 Verification Scope</h3>
        <p className="legal-p">Verification is limited to the information available at the time of assessment.</p>
        <h3 className="legal-h3">6.3 No Warranty</h3>
        <p className="legal-p">A verified listing does not constitute:</p>
        <p className="legal-p">a. A warranty;</p>
        <p className="legal-p">b. A guarantee;</p>
        <p className="legal-p">c. An endorsement;</p>
        <p className="legal-p">d. Insurance;</p>
        <p className="legal-p">e. Certification of safety;</p>
        <p className="legal-p">f. Certification of quality.</p>
        <h3 className="legal-h3">6.4 Reverification Rights</h3>
        <p className="legal-p">Bookam may request additional documentation, conduct further inspections, or suspend listings where concerns arise regarding compliance, quality, safety, or accuracy.</p>
        <h2 className="legal-h2">7. BOOKING PROCESS</h2>
        <h3 className="legal-h3">7.1 User Responsibility</h3>
        <p className="legal-p">Before making a booking, users are responsible for reviewing:</p>
        <p className="legal-p">a. Pricing;</p>
        <p className="legal-p">b. Amenities;</p>
        <p className="legal-p">c. Guest limits;</p>
        <p className="legal-p">d. Cancellation policies;</p>
        <p className="legal-p">e. Refund policies;</p>
        <p className="legal-p">f. Caution fee requirements;</p>
        <p className="legal-p">g. House rules;</p>
        <p className="legal-p">h. Event restrictions;</p>
        <p className="legal-p">i. Booking conditions.</p>
        <h3 className="legal-h3">7.2 Booking Requests</h3>
        <p className="legal-p">Depending on the listing type, a booking may be processed through:</p>
        <p className="legal-p">a. Instant booking;</p>
        <p className="legal-p">b. Booking request;</p>
        <p className="legal-p">c. Provider approval;</p>
        <p className="legal-p">d. Administrative confirmation.</p>
        <h3 className="legal-h3">7.3 Booking Confirmation</h3>
        <p className="legal-p">A booking becomes valid only when Bookam issues an official Booking Confirmation.</p>
        <h3 className="legal-h3">7.4 Payment Does Not Automatically Guarantee Booking</h3>
        <p className="legal-p">Submission of payment, payment authorisation, or deduction of funds does not by itself guarantee a booking.</p>
        <p className="legal-p">A booking is only confirmed when Bookam provides a formal Booking Confirmation.</p>
        <h3 className="legal-h3">7.5 Availability</h3>
        <p className="legal-p">Bookings remain subject to:</p>
        <p className="legal-p">a. Availability;</p>
        <p className="legal-p">b. Provider acceptance;</p>
        <p className="legal-p">c. Payment verification;</p>
        <p className="legal-p">d. Compliance checks;</p>
        <p className="legal-p">e. Platform approval.</p>
        <h3 className="legal-h3">7.6 Accurate Booking Information</h3>
        <p className="legal-p">Users are responsible for ensuring the accuracy of:</p>
        <p className="legal-p">a. Dates;</p>
        <p className="legal-p">b. Number of guests;</p>
        <p className="legal-p">c. Event details;</p>
        <p className="legal-p">d. Contact information;</p>
        <p className="legal-p">e. Special requests.</p>
        <p className="legal-p">Bookam shall not be responsible for losses arising from inaccurate information supplied by users.</p>
        <h3 className="legal-h3">7.7 Booking Refusal</h3>
        <p className="legal-p">Bookam reserves the right to decline, suspend, or cancel bookings where:</p>
        <p className="legal-p">a. Fraud is suspected;</p>
        <p className="legal-p">b. Payment cannot be verified;</p>
        <p className="legal-p">c. The listing becomes unavailable;</p>
        <p className="legal-p">d. Safety concerns arise;</p>
        <p className="legal-p">e. Regulatory restrictions apply;</p>
        <p className="legal-p">f. The booking violates these Terms.</p>
        <h2 className="legal-part">PART 2</h2>
        <p className="legal-p">PAYMENTS, FEES, CAUTION FEES, REFUNDS, CANCELLATIONS AND REBOOKING</p>
        <h2 className="legal-h2">8. PAYMENTS, FEES AND CHARGES</h2>
        <h3 className="legal-h3">8.1 Platform Payments</h3>
        <p className="legal-p">All payments for bookings made through Bookam shall be processed through payment methods approved by Bookam.</p>
        <p className="legal-p">Users agree not to make payments directly to Providers outside the Platform unless expressly authorized by Bookam.</p>
        <h3 className="legal-h3">8.2 Payment Processing</h3>
        <p className="legal-p">Payments may be processed through third-party payment providers including but not limited to Paystack, Flutterwave, banks, card processors, wallet providers, and other payment service providers.</p>
        <p className="legal-p">Bookam shall not be liable for failures, delays, reversals, interruptions, or errors arising from such third-party payment providers.</p>
        <h3 className="legal-h3">8.3 Service Fees</h3>
        <p className="legal-p">Bookam may charge:</p>
        <p className="legal-p">Service Fees</p>
        <p className="legal-p">Convenience Fees</p>
        <p className="legal-p">Booking Fees</p>
        <p className="legal-p">Processing Fees</p>
        <p className="legal-p">Administrative Fees</p>
        <p className="legal-p">Such fees shall be disclosed before payment.</p>
        <h3 className="legal-h3">8.4 Provider Charges</h3>
        <p className="legal-p">Providers may impose charges including:</p>
        <p className="legal-p">Accommodation Fees</p>
        <p className="legal-p">Venue Fees</p>
        <p className="legal-p">Rental Fees</p>
        <p className="legal-p">Cleaning Fees</p>
        <p className="legal-p">Security Deposits</p>
        <p className="legal-p">Caution Fees</p>
        <p className="legal-p">Event Charges</p>
        <p className="legal-p">Utility Charges</p>
        <p className="legal-p">Incidental Charges</p>
        <p className="legal-p">where disclosed before booking confirmation.</p>
        <h3 className="legal-h3">8.5 Taxes</h3>
        <p className="legal-p">Applicable taxes, levies, government charges, and statutory fees may be included or separately displayed as required by law.</p>
        <h3 className="legal-h3">8.6 Failed Transactions</h3>
        <p className="legal-p">Bookam shall not be liable for:</p>
        <p className="legal-p">Failed payments</p>
        <p className="legal-p">Delayed settlements</p>
        <p className="legal-p">Duplicate debits</p>
        <p className="legal-p">Reversed transactions</p>
        <p className="legal-p">Banking errors</p>
        <p className="legal-p">Card issuer restrictions</p>
        <p className="legal-p">Payment gateway downtime</p>
        <p className="legal-p">Users shall cooperate with Bookam in resolving payment-related issues.</p>
        <h3 className="legal-h3">8.7 Prohibition of Off-Platform Transactions</h3>
        <p className="legal-p">Users and Providers shall not circumvent the Platform by arranging bookings or payments outside Bookam after initial contact through the Platform.</p>
        <p className="legal-p">Violation may result in suspension, account termination, penalties, or legal action.</p>
        <h2 className="legal-h2">9. BOOKAM WALLET</h2>
        <h3 className="legal-h3">9.1 Wallet Services</h3>
        <p className="legal-p">Bookam may maintain a digital wallet system allowing users to receive:</p>
        <p className="legal-p">Refunds</p>
        <p className="legal-p">Credits</p>
        <p className="legal-p">Promotional rewards</p>
        <p className="legal-p">Booking compensation</p>
        <p className="legal-p">Loyalty benefits</p>
        <h3 className="legal-h3">9.2 Wallet Usage</h3>
        <p className="legal-p">Wallet balances may be used toward future bookings made through Bookam.</p>
        <h3 className="legal-h3">9.3 Non-Bank Account</h3>
        <p className="legal-p">The Bookam Wallet is not a bank account and does not earn interest.</p>
        <h3 className="legal-h3">9.4 Withdrawal Rights</h3>
        <p className="legal-p">Bookam may permit or restrict wallet withdrawals depending on applicable regulations, payment provider requirements, fraud prevention policies, or promotional conditions.</p>
        <h3 className="legal-h3">9.5 Fraud Prevention</h3>
        <p className="legal-p">Bookam reserves the right to freeze wallet balances pending investigation of suspicious transactions.</p>
        <h2 className="legal-h2">10. CAUTION FEE / SECURITY DEPOSIT</h2>
        <h3 className="legal-h3">10.1 Purpose</h3>
        <p className="legal-p">Certain bookings may require a caution fee or security deposit to cover:</p>
        <p className="legal-p">Property damage</p>
        <p className="legal-p">Missing items</p>
        <p className="legal-p">Excessive cleaning</p>
        <p className="legal-p">Unauthorized guests</p>
        <p className="legal-p">Overstays</p>
        <p className="legal-p">Event violations</p>
        <p className="legal-p">Vehicle damage</p>
        <p className="legal-p">Traffic penalties</p>
        <p className="legal-p">Other losses caused by the User</p>
        <h3 className="legal-h3">10.2 Collection</h3>
        <p className="legal-p">The caution fee may be collected:</p>
        <p className="legal-p">At booking;</p>
        <p className="legal-p">Before check-in;</p>
        <p className="legal-p">Upon arrival;</p>
        <p className="legal-p">Through the Platform;</p>
        <p className="legal-p">Through an approved payment processor.</p>
        <h3 className="legal-h3">10.3 Holding Period</h3>
        <p className="legal-p">The caution fee may be held until:</p>
        <p className="legal-p">Completion of stay;</p>
        <p className="legal-p">Event conclusion;</p>
        <p className="legal-p">Vehicle return;</p>
        <p className="legal-p">Completion of inspection.</p>
        <h3 className="legal-h3">10.4 Deductions</h3>
        <p className="legal-p">Deductions may be made where evidence establishes:</p>
        <p className="legal-p">Damage</p>
        <p className="legal-p">Theft</p>
        <p className="legal-p">Rule violations</p>
        <p className="legal-p">Excessive cleaning costs</p>
        <p className="legal-p">Repair expenses</p>
        <p className="legal-p">Outstanding fees</p>
        <h3 className="legal-h3">10.5 Evidence Requirement</h3>
        <p className="legal-p">Providers must submit reasonable evidence including:</p>
        <p className="legal-p">Photos</p>
        <p className="legal-p">Videos</p>
        <p className="legal-p">Repair invoices</p>
        <p className="legal-p">Inventory records</p>
        <p className="legal-p">Incident reports</p>
        <p className="legal-p">before deductions are approved.</p>
        <h3 className="legal-h3">10.6 User Disputes</h3>
        <p className="legal-p">Users may dispute deductions within seven (7) days of receiving notice.</p>
        <h3 className="legal-h3">10.7 Platform Review</h3>
        <p className="legal-p">Bookam may review evidence submitted by both parties but does not act as a court, insurer, or independent expert.</p>
        <h3 className="legal-h3">10.8 Refund Timeline</h3>
        <p className="legal-p">Undisputed caution fee balances shall generally be released within 7-21 business days subject to payment processing timelines.</p>
        <h2 className="legal-h2">11. CANCELLATIONS, REFUNDS AND NO-SHOWS</h2>
        <h3 className="legal-h3">11.1 Booking-Specific Policies</h3>
        <p className="legal-p">Cancellation and refund terms may vary depending on:</p>
        <p className="legal-p">Property</p>
        <p className="legal-p">Hotel</p>
        <p className="legal-p">Event Centre</p>
        <p className="legal-p">Vehicle</p>
        <p className="legal-p">Yacht</p>
        <p className="legal-p">Provider requirements</p>
        <h3 className="legal-h3">11.2 Display Before Payment</h3>
        <p className="legal-p">Applicable cancellation terms shall be displayed before payment.</p>
        <h3 className="legal-h3">11.3 User Cancellations</h3>
        <p className="legal-p">Users may cancel bookings through the Platform.</p>
        <p className="legal-p">Refund eligibility shall depend on:</p>
        <p className="legal-p">Cancellation timing;</p>
        <p className="legal-p">Provider policy;</p>
        <p className="legal-p">Service category;</p>
        <p className="legal-p">Costs already incurred.</p>
        <h3 className="legal-h3">11.4 Administrative Cancellation Fee</h3>
        <p className="legal-p">Bookam may charge a cancellation processing fee where a booking is cancelled after confirmation.</p>
        <h3 className="legal-h3">11.5 Provider Cancellation</h3>
        <p className="legal-p">Where a Provider cancels a confirmed booking:</p>
        <p className="legal-p">Bookam may:</p>
        <p className="legal-p">Provide alternative options;</p>
        <p className="legal-p">Facilitate rebooking;</p>
        <p className="legal-p">Issue credits;</p>
        <p className="legal-p">Process refunds.</p>
        <p className="legal-p">Bookam does not guarantee identical replacement accommodations or services.</p>
        <h3 className="legal-h3">11.6 No-Shows</h3>
        <p className="legal-p">Failure to attend, check in, occupy, or use a booked service may result in partial or complete forfeiture of amounts paid.</p>
        <h3 className="legal-h3">11.7 Non-Refundable Fees</h3>
        <p className="legal-p">The following may be non-refundable:</p>
        <p className="legal-p">Payment processing fees</p>
        <p className="legal-p">Gateway charges</p>
        <p className="legal-p">Service fees</p>
        <p className="legal-p">Administrative charges</p>
        <p className="legal-p">where disclosed.</p>
        <h3 className="legal-h3">11.8 Refund Processing</h3>
        <p className="legal-p">Approved refunds shall be processed through:</p>
        <p className="legal-p">Original payment method;</p>
        <p className="legal-p">Wallet credit;</p>
        <p className="legal-p">Alternative approved method.</p>
        <h3 className="legal-h3">11.9 Refund Abuse</h3>
        <p className="legal-p">Bookam may reject refund requests that are:</p>
        <p className="legal-p">Fraudulent;</p>
        <p className="legal-p">Repetitive;</p>
        <p className="legal-p">Abusive;</p>
        <p className="legal-p">Unsupported by evidence.</p>
        <h2 className="legal-h2">12. RESCHEDULING AND REBOOKING</h2>
        <h3 className="legal-h3">12.1 User Requests</h3>
        <p className="legal-p">Users may request:</p>
        <p className="legal-p">Date changes</p>
        <p className="legal-p">Guest changes</p>
        <p className="legal-p">Event changes</p>
        <p className="legal-p">Vehicle changes</p>
        <p className="legal-p">Room upgrades</p>
        <p className="legal-p">subject to availability.</p>
        <h3 className="legal-h3">12.2 Rescheduling Fees</h3>
        <p className="legal-p">Where a rescheduling request is made after timelines specified by the Provider, administrative fees or provider penalties may apply.</p>
        <h3 className="legal-h3">12.3 No Guaranteed Rescheduling</h3>
        <p className="legal-p">Rescheduling requests are subject to:</p>
        <p className="legal-p">Availability;</p>
        <p className="legal-p">Provider approval;</p>
        <p className="legal-p">Applicable fees.</p>
        <h3 className="legal-h3">12.4 Alternative Bookings</h3>
        <p className="legal-p">Bookam may assist users in finding alternative listings where available.</p>
        <h3 className="legal-h3">12.5 Consequential Costs</h3>
        <p className="legal-p">Bookam shall not be liable for:</p>
        <p className="legal-p">Transport costs;</p>
        <p className="legal-p">Vendor costs;</p>
        <p className="legal-p">Decoration expenses;</p>
        <p className="legal-p">Lost profits;</p>
        <p className="legal-p">Replacement accommodation costs;</p>
        <p className="legal-p">Business losses.</p>
        <h2 className="legal-part">PART 3</h2>
        <p className="legal-p">USER CONDUCT, CATEGORY-SPECIFIC TERMS AND PROVIDER RESPONSIBILITIES</p>
        <h2 className="legal-h2">13. USER CONDUCT</h2>
        <p className="legal-p">Users shall:</p>
        <p className="legal-p">Comply with all rules;</p>
        <p className="legal-p">Respect providers and staff;</p>
        <p className="legal-p">Observe occupancy limits;</p>
        <p className="legal-p">Use properties lawfully.</p>
        <p className="legal-p">Users shall not:</p>
        <p className="legal-p">Engage in criminal conduct;</p>
        <p className="legal-p">Host unauthorized parties;</p>
        <p className="legal-p">Damage property;</p>
        <p className="legal-p">Disturb neighbours;</p>
        <p className="legal-p">Conduct illegal activities;</p>
        <p className="legal-p">Use false identities.</p>
        <p className="legal-p">The booking User remains responsible for all guests, invitees, vendors, attendees, and occupants.</p>
        <h2 className="legal-h2">14. SHORTLETS AND APARTMENTS</h2>
        <p className="legal-p">Users must comply with:</p>
        <p className="legal-p">Check-in procedures;</p>
        <p className="legal-p">Check-out deadlines;</p>
        <p className="legal-p">Occupancy limits;</p>
        <p className="legal-p">House rules;</p>
        <p className="legal-p">Noise restrictions.</p>
        <p className="legal-p">Overstays may attract additional charges.</p>
        <p className="legal-p">Unauthorized parties may result in immediate termination of the booking without refund.</p>
        <h2 className="legal-h2">15. HOTELS</h2>
        <p className="legal-p">Hotel bookings remain subject to:</p>
        <p className="legal-p">Hotel rules;</p>
        <p className="legal-p">Identification requirements;</p>
        <p className="legal-p">Check-in procedures;</p>
        <p className="legal-p">Capacity restrictions.</p>
        <p className="legal-p">Hotels may substitute rooms of similar category where necessary.</p>
        <p className="legal-p">Incidental charges imposed by hotels remain the responsibility of the User.</p>
        <h2 className="legal-h2">16. EVENT CENTRES</h2>
        <p className="legal-p">Users must comply with:</p>
        <p className="legal-p">Venue capacity limits;</p>
        <p className="legal-p">Setup timelines;</p>
        <p className="legal-p">Cleanup requirements;</p>
        <p className="legal-p">Security procedures;</p>
        <p className="legal-p">Decoration restrictions;</p>
        <p className="legal-p">Noise regulations.</p>
        <p className="legal-p">Users remain responsible for:</p>
        <p className="legal-p">Vendors;</p>
        <p className="legal-p">Guests;</p>
        <p className="legal-p">Event contractors;</p>
        <p className="legal-p">Damages caused during events.</p>
        <h2 className="legal-h2">17. CAR RENTALS</h2>
        <h3 className="legal-h3">17.1 Driver Requirements</h3>
        <p className="legal-p">Drivers must possess valid licenses and meet Provider eligibility requirements.</p>
        <h3 className="legal-h3">17.2 Vehicle Usage</h3>
        <p className="legal-p">Vehicles shall not be used:</p>
        <p className="legal-p">For criminal activities;</p>
        <p className="legal-p">Racing;</p>
        <p className="legal-p">Reckless driving;</p>
        <p className="legal-p">Unauthorized commercial activities.</p>
        <h3 className="legal-h3">17.3 Damage Liability</h3>
        <p className="legal-p">Users remain liable for:</p>
        <p className="legal-p">Vehicle damage;</p>
        <p className="legal-p">Traffic violations;</p>
        <p className="legal-p">Impoundment costs;</p>
        <p className="legal-p">Towing charges;</p>
        <p className="legal-p">Fines.</p>
        <h3 className="legal-h3">17.4 Late Returns</h3>
        <p className="legal-p">Late returns may attract additional charges.</p>
        <h2 className="legal-h2">18. YACHT RENTALS</h2>
        <p className="legal-p">Users must comply with:</p>
        <p className="legal-p">Passenger limits;</p>
        <p className="legal-p">Safety requirements;</p>
        <p className="legal-p">Crew instructions;</p>
        <p className="legal-p">Maritime regulations.</p>
        <p className="legal-p">Weather conditions may result in cancellation or postponement.</p>
        <p className="legal-p">Bookam is not responsible for weather-related interruptions.</p>
        <h2 className="legal-h2">19. PROVIDER RESPONSIBILITIES</h2>
        <p className="legal-p">Providers shall:</p>
        <p className="legal-p">Have authority to list;</p>
        <p className="legal-p">Maintain accurate information;</p>
        <p className="legal-p">Honour confirmed bookings;</p>
        <p className="legal-p">Maintain lawful operations;</p>
        <p className="legal-p">Comply with regulations;</p>
        <p className="legal-p">Treat users professionally.</p>
        <p className="legal-p">Providers remain solely responsible for:</p>
        <p className="legal-p">Property condition;</p>
        <p className="legal-p">Safety;</p>
        <p className="legal-p">Maintenance;</p>
        <p className="legal-p">Staff conduct;</p>
        <p className="legal-p">Legal compliance.</p>
        <h2 className="legal-part">PART 4</h2>
        <p className="legal-p">REVIEWS, COMPLAINTS, TERMINATION, LIABILITY, DATA PROTECTION AND GENERAL PROVISIONS</p>
        <h2 className="legal-h2">20. REVIEWS AND RATINGS</h2>
        <p className="legal-p">Users may submit reviews following completed bookings.</p>
        <p className="legal-p">Reviews must be:</p>
        <p className="legal-p">Truthful;</p>
        <p className="legal-p">Relevant;</p>
        <p className="legal-p">Respectful.</p>
        <p className="legal-p">Bookam may remove reviews that are:</p>
        <p className="legal-p">False;</p>
        <p className="legal-p">Defamatory;</p>
        <p className="legal-p">Abusive;</p>
        <p className="legal-p">Fraudulent;</p>
        <p className="legal-p">Misleading.</p>
        <h2 className="legal-h2">21. PROHIBITED USES</h2>
        <p className="legal-p">Users shall not:</p>
        <p className="legal-p">Commit fraud;</p>
        <p className="legal-p">Abuse chargeback systems;</p>
        <p className="legal-p">Scrape Platform data;</p>
        <p className="legal-p">Bypass Platform fees;</p>
        <p className="legal-p">Impersonate others;</p>
        <p className="legal-p">Disrupt Platform operations;</p>
        <p className="legal-p">Misuse personal information.</p>
        <h2 className="legal-h2">22. COMPLAINTS AND DISPUTE HANDLING</h2>
        <p className="legal-p">Users may submit complaints through:</p>
        <p className="legal-p">Email;</p>
        <p className="legal-p">In-app support;</p>
        <p className="legal-p">WhatsApp support;</p>
        <p className="legal-p">Customer service channels.</p>
        <p className="legal-p">Bookam may request evidence from all parties.</p>
        <p className="legal-p">Bookam may facilitate discussions but does not guarantee resolution of every dispute.</p>
        <h2 className="legal-h2">23. SUSPENSION AND TERMINATION</h2>
        <p className="legal-p">Bookam may suspend:</p>
        <p className="legal-p">Users;</p>
        <p className="legal-p">Providers;</p>
        <p className="legal-p">Listings;</p>
        <p className="legal-p">Accounts;</p>
        <p className="legal-p">where necessary to protect the Platform.</p>
        <p className="legal-p">Termination shall not affect:</p>
        <p className="legal-p">Outstanding liabilities;</p>
        <p className="legal-p">Damage claims;</p>
        <p className="legal-p">Refund obligations;</p>
        <p className="legal-p">Indemnity rights.</p>
        <h2 className="legal-h2">24. DISCLAIMERS</h2>
        <p className="legal-p">The Platform is provided on an “AS IS” and “AS AVAILABLE” basis.</p>
        <p className="legal-p">Bookam makes no guarantees regarding:</p>
        <p className="legal-p">Availability;</p>
        <p className="legal-p">Provider performance;</p>
        <p className="legal-p">Property condition;</p>
        <p className="legal-p">User satisfaction;</p>
        <p className="legal-p">Continuous operation.</p>
        <p className="legal-p">Verification does not constitute a warranty.</p>
        <h2 className="legal-h2">25. LIMITATION OF LIABILITY</h2>
        <p className="legal-p">To the fullest extent permitted by law:</p>
        <p className="legal-p">Bookam shall not be liable for:</p>
        <p className="legal-p">Provider conduct;</p>
        <p className="legal-p">Property damage;</p>
        <p className="legal-p">Theft;</p>
        <p className="legal-p">Personal injury;</p>
        <p className="legal-p">Event disruptions;</p>
        <p className="legal-p">Transport disruptions;</p>
        <p className="legal-p">Utility failures;</p>
        <p className="legal-p">Security incidents.</p>
        <p className="legal-p">Bookam’s total liability shall not exceed the amount paid through the Platform for the affected booking.</p>
        <p className="legal-p">Nothing limits liability for fraud or wilful misconduct where such limitation is prohibited by law.</p>
        <h2 className="legal-h2">26. INDEMNITY</h2>
        <p className="legal-p">Users agree to indemnify Bookam against claims arising from:</p>
        <p className="legal-p">Breach of these Terms;</p>
        <p className="legal-p">Fraud;</p>
        <p className="legal-p">Property damage;</p>
        <p className="legal-p">Illegal activities;</p>
        <p className="legal-p">Unauthorized events;</p>
        <p className="legal-p">Payment disputes.</p>
        <p className="legal-p">Providers agree to indemnify Bookam against claims arising from:</p>
        <p className="legal-p">Inaccurate listings;</p>
        <p className="legal-p">Unsafe properties;</p>
        <p className="legal-p">Regulatory breaches;</p>
        <p className="legal-p">Guest injuries;</p>
        <p className="legal-p">Tax violations;</p>
        <p className="legal-p">Hidden charges.</p>
        <h2 className="legal-h2">27. INTELLECTUAL PROPERTY</h2>
        <p className="legal-p">All rights in:</p>
        <p className="legal-p">Bookam;</p>
        <p className="legal-p">Logos;</p>
        <p className="legal-p">Software;</p>
        <p className="legal-p">Designs;</p>
        <p className="legal-p">Databases;</p>
        <p className="legal-p">Content;</p>
        <p className="legal-p">belong to BookamFast Nigeria Ltd..</p>
        <p className="legal-p">No content may be copied, reproduced, or exploited without written permission.</p>
        <h2 className="legal-h2">28. PRIVACY AND DATA PROTECTION</h2>
        <p className="legal-p">Bookam processes personal data in accordance with its Privacy Policy and applicable Nigerian data protection laws, including the Nigeria Data Protection Act (NDPA).</p>
        <p className="legal-p">Users consent to the sharing of booking information with Providers as necessary to fulfil bookings.</p>
        <p className="legal-p">Providers shall not misuse user information.</p>
        <h2 className="legal-h2">29. THIRD-PARTY SERVICES</h2>
        <p className="legal-p">Bookam may rely on:</p>
        <p className="legal-p">Payment gateways;</p>
        <p className="legal-p">Hosting providers;</p>
        <p className="legal-p">Mapping services;</p>
        <p className="legal-p">Verification providers;</p>
        <p className="legal-p">Communication platforms.</p>
        <p className="legal-p">Bookam shall not be responsible for failures caused by such third-party services.</p>
        <h2 className="legal-h2">30. FORCE MAJEURE</h2>
        <p className="legal-p">Bookam shall not be liable for delays, interruptions, or failures caused by:</p>
        <p className="legal-p">Government actions;</p>
        <p className="legal-p">Civil unrest;</p>
        <p className="legal-p">Power outages;</p>
        <p className="legal-p">Internet failures;</p>
        <p className="legal-p">Natural disasters;</p>
        <p className="legal-p">Epidemics;</p>
        <p className="legal-p">Security emergencies;</p>
        <p className="legal-p">Provider-related disruptions beyond reasonable control.</p>
        <h2 className="legal-h2">31. GOVERNING LAW AND DISPUTE RESOLUTION</h2>
        <p className="legal-p">These Terms shall be governed by the laws of the Federal Republic of Nigeria.</p>
        <p className="legal-p">Parties shall first attempt amicable resolution through Bookam’s dispute process.</p>
        <p className="legal-p">Where unresolved, disputes shall be submitted to mediation and thereafter to the courts of competent jurisdiction in Lagos State, Nigeria.</p>
        <h2 className="legal-h2">32. CHANGES TO TERMS</h2>
        <p className="legal-p">Bookam may amend these Terms from time to time.</p>
        <p className="legal-p">Continued use of the Platform after amendments constitutes acceptance of the revised Terms.</p>
        <h2 className="legal-h2">33. NOTICES</h2>
        <p className="legal-p">Bookam may communicate through:</p>
        <p className="legal-p">Email;</p>
        <p className="legal-p">SMS;</p>
        <p className="legal-p">WhatsApp;</p>
        <p className="legal-p">In-app notifications;</p>
        <p className="legal-p">Phone calls;</p>
        <p className="legal-p">Website announcements.</p>
        <p className="legal-p">Users are responsible for maintaining accurate contact details.</p>
        <h2 className="legal-h2">34. MISCELLANEOUS</h2>
        <p className="legal-p">Entire Agreement</p>
        <p className="legal-p">These Terms, the Privacy Policy, Refund Policy, Caution Fee Policy, and booking-specific rules constitute the entire agreement between the parties.</p>
        <p className="legal-p">Severability</p>
        <p className="legal-p">If any provision is found unenforceable, the remaining provisions shall remain in effect.</p>
        <p className="legal-p">No Waiver</p>
        <p className="legal-p">Failure to enforce any right shall not constitute a waiver.</p>
        <p className="legal-p">Assignment</p>
        <p className="legal-p">Bookam may assign its rights and obligations without prior notice.</p>
        <h2 className="legal-h2">35. CONTACT INFORMATION</h2>
        <p className="legal-p">BookamFast Nigeria Ltd.</p>
        <p className="legal-p">Trading Name: Bookam</p>
        <p className="legal-p"><strong>Customer Support Email:</strong> contact@bookamfast.com</p>
        <p className="legal-p"><strong>General Enquiries:</strong> contact@bookamfast.com</p>
        <p className="legal-p"><strong>Complaints:</strong> contact@bookamfast.com</p>
        <p className="legal-p"><strong>Head Office:</strong> 64 Odunsi Street, Bariga, Lagos State, Nigeria.</p>
        <p className="legal-p">Version: 1.0</p>
    </LegalLayout>
  );
}